name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: set yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DATASOURCE_URL }}
          spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
          spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
          spring.rabbitmq.host: ${{ secrets.EC2_HOST }}
          jwt.secret: ${{ secrets.JWT_SECRET }}
      - name: build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker image build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/funfit_auth .
          docker push ${{ secrets.DOCKER_USERNAME }}/funfit_auth

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PUBLIC_EC2_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Private EC2 via Public EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.PUBLIC_EC2_HOST }} << 'EOF'
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'ENDSSH'
              sudo docker pull ${{ secrets.DOCKER_USERNAME }}/funfit_auth

              existing_container=$(docker ps -q -f name=funfit_auth)
              if [ -n "$existing_container" ]; then
                docker rm -f $existing_container
              fi

              docker run -d --name funfit_auth -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/funfit_auth:latest
              docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -d rabbitmq:management
            ENDSSH
          EOF



#      - name: deploy to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.PUBLIC_EC2_HOST }}
#          username: ubuntu
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script: |
#            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/funfit_auth
#
#            existing_container=$(docker ps -q -f name=funfit_auth)
#            if [ -n "$existing_container" ]; then
#            docker rm -f $existing_container
#            fi
#
#            docker run -d --name funfit_auth -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/funfit_auth:latest
#            docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -d rabbitmq:management
#            EOF
            

#        with:
#          host: ${{ secrets.PUBLIC_EC2_HOST }}
#          username: ubuntu
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script: |
#            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/funfit_auth
#
#            existing_container=$(docker ps -q -f name=funfit_auth)
#            if [ -n "$existing_container" ]; then
#            docker rm -f $existing_container
#            fi
#
#            docker run -d --name funfit_auth -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/funfit_auth:latest
#            docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -d rabbitmq:management
#            EOF

#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ubuntu
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script: |
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/funfit_auth
#
#            existing_container=$(docker ps -q -f name=funfit_auth)
#            if [ -n "$existing_container" ]; then
#            docker rm -f $existing_container
#            fi
#
#            docker run -d --name funfit_auth -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/funfit_auth:latest
#            docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -d rabbitmq:management
